export const LIST_PATH = '/projects'
export const ACCOUNT_PATH = '/account'
export const LOGIN_PATH = '/login'
export const SIGNUP_PATH = '/signup'
export const FAQ_PATH = '/faq'
export const ABOUT_PATH = '/signup'
